"""News items table for storing aggregated feed content."""

from datetime import datetime
from enum import Enum
from typing import Optional

from sqlalchemy import UniqueConstraint
from sqlmodel import Field, SQLModel


class NewsItemTag(str, Enum):
    """Classification tags for news items."""

    RISER = "Riser"
    FALLER = "Faller"
    ANALYSIS = "Analysis"
    HIGHLIGHT = "Highlight"


class NewsItem(SQLModel, table=True):  # type: ignore[call-arg]
    """A news item from an aggregated feed source.

    Stores both original content from the feed and AI-generated fields
    (summary, tag classification).
    """

    __tablename__ = "news_items"
    __table_args__ = (
        UniqueConstraint(
            "source_id", "external_id", name="uq_news_items_source_external"
        ),
    )

    id: Optional[int] = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="news_sources.id", index=True)
    external_id: str = Field(index=True)  # RSS guid for deduplication

    # Original content from feed
    title: str
    description: Optional[str] = Field(default=None)  # RSS description field
    url: str
    image_url: Optional[str] = Field(default=None)  # From RSS enclosure
    author: Optional[str] = Field(default=None)  # From dc:creator

    # AI-generated fields
    summary: Optional[str] = Field(default=None)  # AI-generated byline

    # Classification
    tag: NewsItemTag = Field(default=NewsItemTag.ANALYSIS)

    # Timestamps
    published_at: datetime = Field(index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Future: player association
    player_id: Optional[int] = Field(default=None, foreign_key="players_master.id")
