"""News items table for storing aggregated feed content."""

from datetime import datetime
from enum import Enum
from typing import Optional

from sqlalchemy import UniqueConstraint
from sqlmodel import Field, SQLModel


class NewsItemTag(str, Enum):
    """Classification tags for news items."""

    SCOUTING_REPORT = "Scouting Report"
    # Deep dive on a single prospect: strengths, weaknesses, role projection, film notes

    BIG_BOARD = "Big Board"
    # Rankings or tiers of prospects (Top 60/100, positional boards, tier lists)

    MOCK_DRAFT = "Mock Draft"
    # Pick-by-pick projections, lottery mocks, team outcome simulations

    TIER_UPDATE = "Tier Update"
    # Movement between tiers, re-grouping of prospects, stock context without single-game focus

    GAME_RECAP = "Game Recap"
    # Prospect performance tied to a specific game, slate, or tournament

    FILM_STUDY = "Film Study"
    # Play-type or tape-driven breakdowns (possessions, schemes, tendencies)

    SKILL_THEME = "Skill Theme"
    # Cross-prospect analysis centered on a trait, archetype, or skill

    TEAM_FIT = "Team Fit"
    # Prospect-to-NBA-team fit, roster context, needs-based analysis

    DRAFT_INTEL = "Draft Intel"
    # Rumors, workouts, measurements, agent/team chatter, behind-the-scenes info

    STATS_ANALYSIS = "Statistical Analysis"
    # Statistical models, data-driven analysis, comps, methodology


class NewsItem(SQLModel, table=True):  # type: ignore[call-arg]
    """A news item from an aggregated feed source.

    Stores both original content from the feed and AI-generated fields
    (summary, tag classification).
    """

    __tablename__ = "news_items"
    __table_args__ = (
        UniqueConstraint(
            "source_id", "external_id", name="uq_news_items_source_external"
        ),
    )

    id: Optional[int] = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="news_sources.id", index=True)
    external_id: str = Field(index=True)  # RSS guid for deduplication

    # Original content from feed
    title: str
    description: Optional[str] = Field(default=None)  # RSS description field
    url: str
    image_url: Optional[str] = Field(default=None)  # From RSS enclosure
    author: Optional[str] = Field(default=None)  # From dc:creator

    # AI-generated fields
    summary: Optional[str] = Field(default=None)  # AI-generated byline

    # Classification
    tag: NewsItemTag = Field(default=NewsItemTag.SCOUTING_REPORT)

    # Timestamps
    published_at: datetime = Field(index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Future: player association
    player_id: Optional[int] = Field(default=None, foreign_key="players_master.id")
