"""Remove players table

Revision ID: 9ce336751346
Revises: f1a2b3c4d5e6
Create Date: 2025-12-01 01:07:18.753755
"""

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "9ce336751346"
down_revision = "f1a2b3c4d5e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consensus_mocks_current_rank"), table_name="consensus_mocks")
    op.drop_index(op.f("ix_consensus_mocks_player_id"), table_name="consensus_mocks")
    op.drop_table("consensus_mocks")
    op.drop_index(op.f("ix_players_deleted_at"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_news_feed_player_id"), table_name="news_feed")
    op.drop_index(op.f("ix_news_feed_published_at"), table_name="news_feed")
    op.drop_table("news_feed")
    op.drop_index(
        op.f("ix_player_stock_history_player_id"), table_name="player_stock_history"
    )
    op.drop_index(
        op.f("ix_player_stock_history_recorded_at"), table_name="player_stock_history"
    )
    op.drop_table("player_stock_history")
    op.drop_index(op.f("ix_playerstock_player_id"), table_name="playerstock")
    op.drop_table("playerstock")
    op.drop_index(op.f("ix_newsitem_player_id"), table_name="newsitem")
    op.drop_table("newsitem")
    op.drop_index(op.f("ix_consensusmock_player_id"), table_name="consensusmock")
    op.drop_table("consensusmock")
    op.alter_column(
        "combine_shooting_results",
        "ingested_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "combine_shooting_results",
        "ingested_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.create_table(
        "consensusmock",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("prev_rank", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("team_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "avg_rank",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "volatility",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("consensusmock_pkey")),
    )
    op.create_index(
        op.f("ix_consensusmock_player_id"), "consensusmock", ["player_id"], unique=False
    )
    op.create_table(
        "newsitem",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("sentiment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("newsitem_pkey")),
    )
    op.create_index(
        op.f("ix_newsitem_player_id"), "newsitem", ["player_id"], unique=False
    )
    op.create_table(
        "playerstock",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("buzz_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("playerstock_pkey")),
    )
    op.create_index(
        op.f("ix_playerstock_player_id"), "playerstock", ["player_id"], unique=False
    )
    op.create_table(
        "player_stock_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("buzz_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "recorded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players_master.id"],
            name=op.f("player_stock_history_player_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("player_stock_history_pkey")),
    )
    op.create_index(
        op.f("ix_player_stock_history_recorded_at"),
        "player_stock_history",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_stock_history_player_id"),
        "player_stock_history",
        ["player_id"],
        unique=False,
    )
    op.create_table(
        "news_feed",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("summary", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sentiment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players_master.id"], name=op.f("news_feed_player_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("news_feed_pkey")),
    )
    op.create_index(
        op.f("ix_news_feed_published_at"), "news_feed", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_news_feed_player_id"), "news_feed", ["player_id"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "player_position",
            postgresql.ENUM("g", "f", "c", name="player_position_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("school", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("players_pkey")),
    )
    op.create_index(
        op.f("ix_players_deleted_at"), "players", ["deleted_at"], unique=False
    )
    op.create_table(
        "consensus_mocks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("current_rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("previous_rank", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "avg_rank",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("best_rank", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("worst_rank", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("projected_team", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players_master.id"],
            name=op.f("consensus_mocks_player_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("consensus_mocks_pkey")),
    )
    op.create_index(
        op.f("ix_consensus_mocks_player_id"),
        "consensus_mocks",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consensus_mocks_current_rank"),
        "consensus_mocks",
        ["current_rank"],
        unique=False,
    )
    # ### end Alembic commands ###
