"""feat: metric snapshots version/current + CASCADE FKs

Revision ID: 9ebe32d1120c
Revises: 7f2c9f6d0e2a
Create Date: 2025-11-16 23:27:31.603012
"""

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa

revision = "9ebe32d1120c"
down_revision = "7f2c9f6d0e2a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_combine_agility_pos"), table_name="combine_agility")
    op.create_index(
        op.f("ix_combine_agility_position_fine"),
        "combine_agility",
        ["position_fine"],
        unique=False,
    )
    op.create_index(
        op.f("ix_combine_agility_raw_position"),
        "combine_agility",
        ["raw_position"],
        unique=False,
    )
    op.drop_index(op.f("ix_combine_anthro_pos"), table_name="combine_anthro")
    op.create_index(
        op.f("ix_combine_anthro_position_fine"),
        "combine_anthro",
        ["position_fine"],
        unique=False,
    )
    op.create_index(
        op.f("ix_combine_anthro_raw_position"),
        "combine_anthro",
        ["raw_position"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_combine_shooting_results_pos"), table_name="combine_shooting_results"
    )
    op.create_index(
        op.f("ix_combine_shooting_results_position_fine"),
        "combine_shooting_results",
        ["position_fine"],
        unique=False,
    )
    op.create_index(
        op.f("ix_combine_shooting_results_raw_position"),
        "combine_shooting_results",
        ["raw_position"],
        unique=False,
    )
    op.add_column(
        "metric_snapshots", sa.Column("version", sa.Integer(), nullable=False)
    )
    op.add_column(
        "metric_snapshots", sa.Column("is_current", sa.Boolean(), nullable=False)
    )
    op.drop_constraint(
        op.f("uq_metric_snapshots_run"), "metric_snapshots", type_="unique"
    )
    op.create_index(
        op.f("ix_metric_snapshots_position_scope_fine"),
        "metric_snapshots",
        ["position_scope_fine"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_snapshots_position_scope_parent"),
        "metric_snapshots",
        ["position_scope_parent"],
        unique=False,
    )
    op.create_index(
        "uq_metric_snapshots_current",
        "metric_snapshots",
        ["source", "run_key"],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
    )
    op.create_unique_constraint(
        "uq_metric_snapshots_src_run_ver",
        "metric_snapshots",
        ["source", "run_key", "version"],
    )
    op.alter_column(
        "player_metric_values", "snapshot_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(
        op.f("ix_player_metric_values_snapshot_id"), table_name="player_metric_values"
    )
    op.drop_constraint(
        op.f("player_metric_values_snapshot_id_fkey"),
        "player_metric_values",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "player_metric_values",
        "metric_snapshots",
        ["snapshot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "player_similarity", "snapshot_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(
        op.f("ix_player_similarity_snapshot_id"), table_name="player_similarity"
    )
    op.drop_constraint(
        op.f("player_similarity_snapshot_id_fkey"),
        "player_similarity",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "player_similarity",
        "metric_snapshots",
        ["snapshot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "player_similarity", type_="foreignkey")
    op.create_foreign_key(
        op.f("player_similarity_snapshot_id_fkey"),
        "player_similarity",
        "metric_snapshots",
        ["snapshot_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_player_similarity_snapshot_id"),
        "player_similarity",
        ["snapshot_id"],
        unique=False,
    )
    op.alter_column(
        "player_similarity", "snapshot_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(None, "player_metric_values", type_="foreignkey")
    op.create_foreign_key(
        op.f("player_metric_values_snapshot_id_fkey"),
        "player_metric_values",
        "metric_snapshots",
        ["snapshot_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_player_metric_values_snapshot_id"),
        "player_metric_values",
        ["snapshot_id"],
        unique=False,
    )
    op.alter_column(
        "player_metric_values",
        "snapshot_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "uq_metric_snapshots_src_run_ver", "metric_snapshots", type_="unique"
    )
    op.drop_index(
        "uq_metric_snapshots_current",
        table_name="metric_snapshots",
        postgresql_where=sa.text("is_current = true"),
    )
    op.drop_index(
        op.f("ix_metric_snapshots_position_scope_parent"), table_name="metric_snapshots"
    )
    op.drop_index(
        op.f("ix_metric_snapshots_position_scope_fine"), table_name="metric_snapshots"
    )
    op.create_unique_constraint(
        op.f("uq_metric_snapshots_run"),
        "metric_snapshots",
        ["run_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("metric_snapshots", "is_current")
    op.drop_column("metric_snapshots", "version")
    op.drop_index(
        op.f("ix_combine_shooting_results_raw_position"),
        table_name="combine_shooting_results",
    )
    op.drop_index(
        op.f("ix_combine_shooting_results_position_fine"),
        table_name="combine_shooting_results",
    )
    op.create_index(
        op.f("ix_combine_shooting_results_pos"),
        "combine_shooting_results",
        ["raw_position"],
        unique=False,
    )
    op.drop_index(op.f("ix_combine_anthro_raw_position"), table_name="combine_anthro")
    op.drop_index(op.f("ix_combine_anthro_position_fine"), table_name="combine_anthro")
    op.create_index(
        op.f("ix_combine_anthro_pos"), "combine_anthro", ["raw_position"], unique=False
    )
    op.drop_index(op.f("ix_combine_agility_raw_position"), table_name="combine_agility")
    op.drop_index(
        op.f("ix_combine_agility_position_fine"), table_name="combine_agility"
    )
    op.create_index(
        op.f("ix_combine_agility_pos"),
        "combine_agility",
        ["raw_position"],
        unique=False,
    )
    # ### end Alembic commands ###
