"""add round_label to summer_league_games

Adds the tournament round (from the NBA.com schedule feed's gameSubLabel) to
Summer League games so the Vegas championship bracket can be rendered.

Revision ID: b3d9f17c2a84
Revises: c7d8e9f0a1b2
Create Date: 2026-06-14 16:30:00.000000

"""

from alembic import op  # type: ignore[attr-defined]
import sqlmodel  # noqa: F401  (kept for parity with autogenerated migrations)

# revision identifiers, used by Alembic.
revision = "b3d9f17c2a84"
down_revision = "c7d8e9f0a1b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Idempotent: the "Add Summer League product tables" migration uses
    # SQLModel.metadata.create_all, which on a from-scratch upgrade now reflects
    # this column and creates it already. On an existing DB the column is absent
    # and this adds it. IF NOT EXISTS keeps both paths green.
    op.execute(
        "ALTER TABLE summer_league_games ADD COLUMN IF NOT EXISTS round_label VARCHAR"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE summer_league_games DROP COLUMN IF EXISTS round_label")
