"""feat: add player_status + bio_snapshots + master bio fields

Revision ID: fdb8c05957b9
Revises: 4a25bc30bc2b
Create Date: 2025-11-02 01:36:27.037700
"""

from alembic import op  # type: ignore[attr-defined]
import sqlmodel
import sqlalchemy as sa

revision = "fdb8c05957b9"
down_revision = "4a25bc30bc2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_bio_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.Column("raw_meta_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players_master.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_bio_snapshots_player_id"),
        "player_bio_snapshots",
        ["player_id"],
        unique=False,
    )
    op.create_table(
        "player_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("is_active_nba", sa.Boolean(), nullable=True),
        sa.Column("current_team", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nba_last_season", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("height_in", sa.Integer(), nullable=True),
        sa.Column("weight_lb", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players_master.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", name="uq_player_status_player"),
    )
    op.create_index(
        op.f("ix_player_status_current_team"),
        "player_status",
        ["current_team"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_status_is_active_nba"),
        "player_status",
        ["is_active_nba"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_status_nba_last_season"),
        "player_status",
        ["nba_last_season"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_status_player_id"), "player_status", ["player_id"], unique=False
    )
    op.add_column(
        "players_master",
        sa.Column("birth_city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "players_master",
        sa.Column(
            "birth_state_province", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "players_master",
        sa.Column("birth_country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "players_master",
        sa.Column("school", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "players_master",
        sa.Column("high_school", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "players_master",
        sa.Column("shoots", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "players_master", sa.Column("draft_year", sa.Integer(), nullable=True)
    )
    op.add_column(
        "players_master", sa.Column("draft_round", sa.Integer(), nullable=True)
    )
    op.add_column(
        "players_master", sa.Column("draft_pick", sa.Integer(), nullable=True)
    )
    op.add_column(
        "players_master",
        sa.Column("draft_team", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "players_master", sa.Column("nba_debut_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "players_master",
        sa.Column(
            "nba_debut_season", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_players_master_birth_city"),
        "players_master",
        ["birth_city"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_master_birth_country"),
        "players_master",
        ["birth_country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_master_birth_state_province"),
        "players_master",
        ["birth_state_province"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_master_draft_year"),
        "players_master",
        ["draft_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_master_nba_debut_season"),
        "players_master",
        ["nba_debut_season"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_players_master_nba_debut_season"), table_name="players_master"
    )
    op.drop_index(op.f("ix_players_master_draft_year"), table_name="players_master")
    op.drop_index(
        op.f("ix_players_master_birth_state_province"), table_name="players_master"
    )
    op.drop_index(op.f("ix_players_master_birth_country"), table_name="players_master")
    op.drop_index(op.f("ix_players_master_birth_city"), table_name="players_master")
    op.drop_column("players_master", "nba_debut_season")
    op.drop_column("players_master", "nba_debut_date")
    op.drop_column("players_master", "draft_team")
    op.drop_column("players_master", "draft_pick")
    op.drop_column("players_master", "draft_round")
    op.drop_column("players_master", "draft_year")
    op.drop_column("players_master", "shoots")
    op.drop_column("players_master", "high_school")
    op.drop_column("players_master", "school")
    op.drop_column("players_master", "birth_country")
    op.drop_column("players_master", "birth_state_province")
    op.drop_column("players_master", "birth_city")
    op.drop_index(op.f("ix_player_status_player_id"), table_name="player_status")
    op.drop_index(op.f("ix_player_status_nba_last_season"), table_name="player_status")
    op.drop_index(op.f("ix_player_status_is_active_nba"), table_name="player_status")
    op.drop_index(op.f("ix_player_status_current_team"), table_name="player_status")
    op.drop_table("player_status")
    op.drop_index(
        op.f("ix_player_bio_snapshots_player_id"), table_name="player_bio_snapshots"
    )
    op.drop_table("player_bio_snapshots")
    # ### end Alembic commands ###
