"""Per-file complexity ratchet — counts, not blanket ignores.

Why this exists on top of Ruff's own baseline
---------------------------------------------
``[tool.ruff.lint.per-file-ignores]`` silences a rule for an *entire file*, so once
``desk_read.py`` is listed for ``C901`` a brand-new complexity-15 function in that same file
passes ``ruff check`` untouched. The baseline stops unrelated work from drowning in 265
pre-existing findings, but on its own it is not the ratchet §1.6 asks for — a point raised in
review of PR #673.

This script closes that gap without touching a single source file. It runs the complexity
rules with ``--isolated`` (so ``per-file-ignores`` does not apply), counts findings per
``(file, rule)``, and compares against a committed baseline. Counts may fall, never rise.

The two mechanisms are complementary, not redundant:

* ``per-file-ignores`` keeps ``ruff check`` and editor diagnostics quiet on known debt, and
  still flags a brand-new *file* immediately;
* this ratchet catches growth *inside* the files that baseline forgives.

Why counts rather than inline ``# noqa``
----------------------------------------
Annotating all 265 findings would add a line to each offending function across 94 files —
many of which are already over the file-size threshold, so the annotations would trip the
sibling file-size ratchet and need their own waivers. A counts file keeps the debt out of the
source entirely.

Stale entries fail too. A count that has *dropped* below its baseline is not a free pass —
it is silent regression headroom: the file could climb back to its old allowance with CI
green. Like the FK-coverage and import-contract baselines, an improvement must be locked in
(``make lint.complexity.update``) in the same change that earned it.

Known limit, stated plainly: swapping one violation for another within the same
``(file, rule)`` keeps the count level and passes. The count can never *grow*, which is what
the ratchet is for.

Usage::

    python scripts/check_complexity_ratchet.py            # enforce against the baseline
    python scripts/check_complexity_ratchet.py --update   # rewrite the baseline (after cleanup)
"""

from __future__ import annotations

import argparse
import collections
import json
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
BASELINE_PATH = REPO_ROOT / "complexity-baseline.json"

# Kept in step with [tool.ruff.lint] in pyproject.toml.
RULES = ("C901", "PLR0915", "PLR0913")
EXCLUDES = ("alembic", "tests", ".codex")


def _current_counts() -> dict[str, dict[str, int]]:
    """Return ``{path: {rule: count}}`` for the working tree.

    ``--isolated`` is essential: without it Ruff applies ``per-file-ignores`` and reports
    almost nothing, which would make this ratchet silently vacuous.
    """
    command = [
        "ruff",
        "check",
        "--isolated",
        "--no-cache",
        "--select",
        ",".join(RULES),
        "--output-format",
        "json",
    ]
    for exclude in EXCLUDES:
        command += ["--exclude", exclude]
    command.append(".")

    result = subprocess.run(command, capture_output=True, text=True, cwd=REPO_ROOT)
    if not result.stdout.strip():
        sys.stderr.write(
            "complexity ratchet: ruff produced no output; "
            f"stderr was:\n{result.stderr}\n"
        )
        raise SystemExit(2)

    tally: dict[str, collections.Counter[str]] = collections.defaultdict(
        collections.Counter
    )
    for finding in json.loads(result.stdout):
        path = Path(finding["filename"])
        try:
            relative = path.relative_to(REPO_ROOT).as_posix()
        except ValueError:  # pragma: no cover - ruff always reports inside the repo
            relative = path.as_posix()
        tally[relative][finding["code"]] += 1

    return {
        path: dict(sorted(counts.items())) for path, counts in sorted(tally.items())
    }


def _load_baseline() -> dict[str, dict[str, int]]:
    """Read the committed baseline, or an empty one if it does not exist yet."""
    if not BASELINE_PATH.is_file():
        return {}
    return json.loads(BASELINE_PATH.read_text(encoding="utf-8")).get("counts", {})


def _write_baseline(counts: dict[str, dict[str, int]]) -> None:
    """Write the baseline file with a self-explaining header."""
    payload = {
        "_comment": (
            "Complexity ratchet baseline — counts of C901/PLR0915/PLR0913 findings per file. "
            "Generated by scripts/check_complexity_ratchet.py --update. These numbers may only "
            "go down: CI fails if any count rises or a new file appears. See "
            "docs/plans/programmatic-code-discipline.md 1.6."
        ),
        "counts": counts,
    }
    BASELINE_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def compare(
    current: dict[str, dict[str, int]], baseline: dict[str, dict[str, int]]
) -> tuple[list[str], list[str]]:
    """Return (regressions, improvements) comparing current counts against the baseline."""
    regressions: list[str] = []
    improvements: list[str] = []

    for path, counts in current.items():
        for rule, count in counts.items():
            allowed = baseline.get(path, {}).get(rule, 0)
            if count > allowed:
                where = f"{path} [{rule}]"
                regressions.append(
                    f"{where}: {count} findings, baseline allows {allowed}"
                    + ("  (new file for this rule)" if allowed == 0 else "")
                )
            elif count < allowed:
                improvements.append(f"{path} [{rule}]: {allowed} -> {count}")

    for path, counts in baseline.items():
        for rule, allowed in counts.items():
            if current.get(path, {}).get(rule, 0) == 0 and allowed > 0:
                improvements.append(f"{path} [{rule}]: {allowed} -> 0")

    return sorted(regressions), sorted(improvements)


def main(argv: list[str] | None = None) -> int:
    """Compare current complexity counts against the baseline."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="Rewrite the baseline from the current tree (use after a cleanup).",
    )
    args = parser.parse_args(argv)

    current = _current_counts()

    if args.update:
        _write_baseline(current)
        total = sum(sum(c.values()) for c in current.values())
        print(
            f"complexity baseline updated: {total} findings across {len(current)} files"
        )
        return 0

    regressions, improvements = compare(current, _load_baseline())

    if regressions:
        sys.stderr.write(
            "\n".join(
                [
                    "ERROR: complexity ratchet — new findings beyond the baseline.",
                    "",
                    "Ruff's per-file-ignores would let these through because the file is already",
                    "baselined for the rule; this check exists so it cannot.",
                    "",
                    *regressions,
                    "",
                    "Simplify the new code, or — if the growth is genuinely warranted — run",
                    "`make lint.complexity.update` and explain the increase in the PR.",
                    "",
                ]
            )
        )
        return 1

    if improvements:
        sys.stderr.write(
            "\n".join(
                [
                    "ERROR: complexity ratchet — the baseline is stale.",
                    "",
                    "These counts have dropped below their baseline entries. Left as-is, the",
                    "entries grant silent headroom to regress; the ratchet only ratchets if",
                    "improvements are locked in when they land.",
                    "",
                    *improvements,
                    "",
                    "Run `make lint.complexity.update` and commit complexity-baseline.json",
                    "with this change.",
                    "",
                ]
            )
        )
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
