"""Pydantic request/response models for the news feed."""

from typing import Optional

from sqlmodel import SQLModel


class NewsItemRead(SQLModel):
    """Response model for a news feed item.

    Contains formatted fields ready for display in the UI.
    """

    id: int
    source_name: str  # "Floor and Ceiling"
    title: str
    summary: str  # AI-generated byline
    url: str
    image_url: Optional[str] = None  # Article image or None for placeholder
    author: Optional[str] = None
    time: str  # Relative time "2h", "1d"
    tag: str  # "Riser", "Faller", etc.
    read_more_text: str  # "Read at Floor and Ceiling"
    is_player_specific: bool = False  # True when article mentions this player


class NewsFeedResponse(SQLModel):
    """Response model for paginated news feed."""

    items: list[NewsItemRead]
    total: int
    limit: int
    offset: int


class NewsSourceRead(SQLModel):
    """Response model for a news source (admin view)."""

    id: int
    name: str
    display_name: str
    feed_type: str
    feed_url: str
    is_active: bool
    fetch_interval_minutes: int
    last_fetched_at: Optional[str] = None  # ISO format string


class NewsSourceCreate(SQLModel):
    """Request model for creating a news source."""

    name: str
    display_name: str
    feed_url: str
    feed_type: str = "rss"
    fetch_interval_minutes: int = 30


class IngestionResult(SQLModel):
    """Response model for ingestion cycle results."""

    sources_processed: int
    items_added: int
    items_skipped: int
    mentions_added: int = 0
    errors: list[str]
