name: Deploy to Fly (main)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: fly-main-deploy
      cancel-in-progress: true

    environment:
      name: draft-app-stage
      url: https://draft-app.fly.dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assert Fly token present
        run: test -n "${{ secrets.FLY_API_TOKEN }}" || (echo "Missing FLY_API_TOKEN secret"; exit 1)

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Ensure secrets exist on app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set \
            DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            SECRET_KEY='${{ secrets.SECRET_KEY }}' \
            ENV=prod \
            LOG_LEVEL=INFO \
            ACCESS_LOG=false

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only
