name: Deploy to Fly (main)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: fly-main-deploy
      cancel-in-progress: false

    # Optional: show a "deployment" link on the repo UI
    environment:
      name: draft-app-stage
      url: https://draft-app.fly.dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # Uses app & settings from fly.toml (app = 'draft-app')
          flyctl deploy --remote-only
